# Generated by Django 3.2.9 on 2024-01-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='number',
            new_name='Number',
        ),
    ]
